server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/spring-boot
          jwk-set-uri: http://localhost:8081/realms/spring-boot/protocol/openid-connect/certs

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

  management:
    endpoints:
      web:
        exposure:
          include: '*'
